export const selectors = {
  "class": "class",
  "id": "id",
  "selector": "selector"
};

export const elements = {
  "a": "a",
  "article": "article",
  "audio": "audio",
  "blockquote": "blockquote",
  "body": "body",
  "button": "button",
  "canvas": "canvas",
  "caption": "caption",
  "circle": "Css.Elements.circle",
  "code": "code",
  "col": "col",
  "colgroup": "colgroup",
  "div": "div",
  "ellipse": "ellipse",
  "em": "Css.Elements.em",
  "fieldset": "fieldset",
  "footer": "footer",
  "form": "form",
  "h1": "h1",
  "h2": "h2",
  "h3": "h3",
  "h4": "h4",
  "h5": "h5",
  "h6": "h6",
  "header": "header",
  "hr": "hr",
  "html": "html",
  "i": "i",
  "img": "img",
  "input": "input",
  "label": "label",
  "legend": "legend",
  "li": "li",
  "line": "line",
  "main_": "main_",
  "nav": "nav",
  "ol": "ol",
  "optgroup": "optgroup",
  "option": "option",
  "p": "p",
  "path": "path",
  "polygon": "polygon",
  "polyline": "polyline",
  "pre": "pre",
  "progress": "Css.Elements.progress",
  "rect": "rect",
  "section": "section",
  "select": "select",
  "small": "Css.Elements.small",
  "span": "span",
  "strong": "strong",
  "svg": "svg",
  "table": "Css.Elements.table",
  "tbody": "tbody",
  "td": "td",
  "textarea": "textarea",
  "tfoot": "tfoot",
  "th": "th",
  "thead": "thead",
  "tr": "tr",
  "ul": "ul",
  "video": "video"
};

export const pseudoClasses = {
  ":active": "active",
  ":any": "any",
  ":checked": "checked",
  ":dir": "dir",
  ":disabled": "disabled",
  ":empty": "empty",
  ":enabled": "enabled",
  ":first": "first",
  ":first-child": "firstChild",
  ":first-of-type": "firstOfType",
  ":focus": "focus",
  ":fullscreen": "fullscreen",
  ":hover": "hover",
  ":indeterminate": "indeterminate",
  ":invalid": "invalid",
  ":lang": "lang",
  ":last-child": "lastChild",
  ":last-of-type": "lastOfType",
  ":link": "link",
  ":nth-child": "nthChild",
  ":nth-last-child": "nthLastChild",
  ":nth-last-of-type": "nthLastOfType",
  ":nth": "nthOfType",
  ":only-child": "onlyChild",
  ":only-of-type": "onlyOfType",
  ":optional": "optional",
  ":out-of-range": "outOfRange",
  ":read-write": "readWrite",
  ":required": "required",
  ":root": "root",
  ":scope": "scope",
  ":target": "target",
  ":valid": "valid"
};

export const pseudoElements = {
  "::after": "after",
  "::before": "before",
  "::first-letter": "firstLetter",
  "::first-line": "firstLine",
  "::selection": "selection"
};