exports.selectorLookup = {
  "id": "(#)",
  "class": "(.)",
  "selector": "selector"
};

exports.elements = [
  "a",
  "article",
  "audio",
  "body",
  "button",
  "canvas",
  "caption",
  "code",
  "col",
  "colgroup",
  "div",
  "em",
  "fieldset",
  "footer",
  "form",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "header",
  "hr",
  "html",
  "i",
  "img",
  "input",
  "label",
  "legend",
  "li",
  "main_",
  "nav",
  "ol",
  "optgroup",
  "option",
  "p",
  "pre",
  "progress",
  "section",
  "small",
  "span",
  "strong",
  "table",
  "tbody",
  "td",
  "tfoot",
  "th",
  "thead",
  "tr",
  "ul",
  "video"
];

exports.pseudoClasses = {
  ":active": "active",
  ":any": "any",
  ":checked": "checked",
  ":dir": "dir",
  ":disabled": "disabled",
  ":empty": "empty",
  ":enabled": "enabled",
  ":first": "first",
  ":first-child": "firstChild",
  ":first-of-type": "firstOfType",
  ":focus": "focus",
  ":fullscreen": "fullscreen",
  ":hover": "hover",
  ":indeterminate": "indeterminate",
  ":invalid": "invalid",
  ":lang": "lang",
  ":last-child": "lastChild",
  ":last-of-type": "lastOfType",
  ":link": "link",
  ":nth-child": "nthChild",
  ":nth-last-child": "nthLastChild",
  ":nth-last-of-type": "nthLastOfType",
  ":nth": "nthOfType",
  ":only-child": "onlyChild",
  ":only-of-type": "onlyOfType",
  ":optional": "optional",
  ":out-of-range": "outOfRange",
  ":read-write": "readWrite",
  ":required": "required",
  ":root": "root",
  ":scope": "scope",
  ":target": "target",
  ":valid": "valid"
};

exports.pseudoElements = {
  "::after": "after",
  "::before": "before",
  "::first-letter": "firstLetter",
  "::first-line": "firstLine",
  "::selection": "selection"
};